languages: {en: "English", vi: "Tiếng Việt", ja: "日本語"}
contact:
  max_name_length: 50
  max_email_length: 255
  max_title_length: 255
  min_title_length: 3
  min_content_length: 10
  max_content_length: 255
logs:
  admin_log_path: "log/admin.log"
  log_dir: "log"
  last_ten: 10
